### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by VipulAlgoSoul** [JiaquanYe/TableMASTER-mmocr#61]
Trying to run table recognition demo script in google colab , gdrive mounted and repo is inside gdrive. 
While runninh the table recognition demoscript i am getting error below >>>>>>>

Use load_from_local loader
Traceback (most recent call last):
  File "./table_recognition/demo/demo_cp.py", line 65, in <module>
    master_inference = Recognition_Inference(args.master_config, args.master_checkpoint)
  File "/content/drive/MyDrive/work/TableMASTER-mmocr/table_recognition/table_inference.py", line 99, in __init__
    super().__init__(config_file, checkpoint_file)
  File "/content/drive/MyDrive/work/TableMASTER-mmocr/table_recognition/table_inference.py", line 38, in __init__
    self.model = build_model(config_file, checkpoint_file)
  File "/content/drive/MyDrive/work/TableMASTER-mmocr/table_recognition/table_inference.py", line 25, in build_model
    model = init_detector(config_file, checkpoint=checkpoint_file, device=device)
  File "/content/drive/MyDrive/work/TableMASTER-mmocr/mmdetection-2.11.0/mmdet/apis/inference.py", line 31, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 254, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 148, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp8emb1yyv/tmptcqvifrk.py", line 6, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './tools/data/alphabet/textline_recognition_alphabet.txt'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fe26a3dc940>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 579, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 575, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8emb1yyv/tmptcqvifrk.py'[](url)

**Comment by zjw-gh** [comment]
I have also encountered this problem. Have you solved it？
